name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib postgresql-server-dev-all
      - name: Start PostgreSQL
        run: |
          sudo pg_ctlcluster $(pg_config --version | awk '{print $2}' | cut -d. -f1) main start
      - name: Run tests
        run: |
          make install
          sudo chown -R postgres:postgres .
          sudo -u postgres make installcheck
